#### general settings
name: Testing_loss_back_0222
#name: Testing
use_tb_logger: true #true
model: VideoSR_base
distortion: sr
scale: 4
gpu_ids: [0, 1]

#### datasets
datasets:
  train:
    name: Vimeo7
    mode: Vimeo7
    interval_list: [1]
    random_reverse: true #false
    border_mode: false
    dataroot_GT: /mnt/ssd0/junwoojin/datas/vimeo_septuplet/vimeo7_train_GT.lmdb
    dataroot_LQ: /mnt/ssd0/junwoojin/datas/vimeo_septuplet/vimeo7_train_LR7.lmdb
    cache_keys: Vimeo7_train_keys.pkl

    N_frames: 7
    use_shuffle: true
    n_workers: 4 # per GPU
    batch_size: 24 # 16
    GT_size: 128
    LQ_size: 32
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: Vimeo7
    mode: Vimeo7
    interval_list: [ 1 ]
    random_reverse: true #false
    border_mode: false
    dataroot_GT: /mnt/ssd0/junwoojin/datas/vimeo_septuplet/vimeo7_test_GT.lmdb
    dataroot_LQ: /mnt/ssd0/junwoojin/datas/vimeo_septuplet/vimeo7_test_LR7.lmdb
    cache_keys: Vimeo7_test_keys.pkl

    N_frames: 7
    use_shuffle: false
    n_workers: 4 # per GPU
    batch_size: 1 # 16
    GT_size: 128
    LQ_size: 32
    use_flip: false
    use_rot: false
    color: RGB

#### network structures
network_G:
  which_model_G: Real_STVR
  nf: 64
  nframes: 7
  groups: 8
  front_RBs: 5
  mid_RBs: 0
  back_RBs: 30
  HR_in: false

#### path
path:
  pretrain_model_G: ~
  strict_load: false #true #
  resume_state: /mnt/ssd0/junwoojin/codes/Zooming-Slow-Mo-CVPR-2020/experiments/Testing_loss_back_0222/training_state/111000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1 #4000  # -1: no warm up
  T_period: [150000, 150000, 150000, 150000]
  restarts: [150000, 300000, 450000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 3e3

  manual_seed: 0
#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 3e3
